const actionTypes = {
  REQUEST_ADD_SKILL: "REQUEST_ADD_SKILL",
  RECEIVE_ADD_SKILL: "RECEIVE_ADD_SKILL",
  ERROR_ADD_SKILL: "ERROR_ADD_SKILL",

  REQUEST_EMPLOYEE_SKILL_BY_ID: "REQUEST_EMPLOYEE_SKILL_BY_ID",
  RECEIVE_EMPLOYEE_SKILL_BY_ID: "RECEIVE_EMPLOYEE_SKILL_BY_ID",

  REQUEST_EDIT_SKILL: "REQUEST_EDIT_SKILL",
  RECEIVE_EDIT_SKILL: "RECEIVE_EDIT_SKILL",
  ERROR_EDIT_SKILL: "ERROR_EDIT_SKILL",

  REQUEST_DELETE_SKILL: "REQUEST_DELETE_SKILL",
  RECEIVE_DELETE_SKILL: "RECEIVE_DELETE_SKILL",
  ERROR_DELETE_SKILL: "ERROR_DELETE_SKILL",

  REQUEST_LOAD_SKILLS: "REQUEST_LOAD_SKILLS",
  RECEIVE_LOAD_SKILLS: "RECEIVE_LOAD_SKILLS",
  ERROR_LOAD_SKILLS: "ERROR_LOAD_SKILLS",

  TECHNOLOGY_STACKS: {
    REQUEST_LOAD_TECH_STACKS: "REQUEST_LOAD_TECH_STACKS",
    RECEIVE_LOAD_TECH_STACKS: "RECEIVE_LOAD_TECH_STACKS",
    ERROR_LOAD_TECH_STACKS: "ERROR_LOAD_TECH_STACKS"
  },


  Employee_Skills:
  {
    REQUEST_EMPLOYEE_SKILLS:"REQUEST_EMPLOYEE_SKILLS",
    RECEIVE_EMPLOYEE_SKILLS:"RECEIVE_EMPLOYEE_SKILLS",
    ERROR_EMPLOYEE_SKILLS:"ERROR_EMPLOYEE_SKILLS"
  }

};
export default actionTypes;
